### ISSUE TITLE
constant rerenders with useProfile

### ISSUE THREAD

**Issue by wds4** [ostyjs/nostr-hooks#27]
I am having a problem with continuous rerenders associated with v2.9.11 `useProfile` that I am hoping someone can help me with. 

Note: I have successfully implemented the "memoization" technique to prevent infinite rerenders associated with `useSubscribe`. This seems to be a different issue.

The following is a compact version of the component I am using:

```
import { useProfile } from 'nostr-hooks'

const pubkey = '...'

const ProblemComponent = () => {
    const { profile } = useProfile({ pubkey })
    console.log('component rerendered')
    if (!profile) return <div>no profile</div>
    return <div>name: {profile?.name}</div>
}
```

The above component displays the name as expected. However, in the javascript console I can see the component being rerendered a little more than once per second, seemingly without end.

My implementation is at  `https://github.com/PrettyGoodFreedomTech/nostr-react-dashboard-template`, using nostr-hooks v2.9.11. The "problem" component can be located at `src/views/hellowWorld/testPage3/testPageBody.js`. I implemented a workaround using `useNdk ` to build a function `asyncFetchProfile` which is at `src/helpers/ndk` and successfully implemented at `src/views/hellowWorld/testPage4/testPageBody.js`. For now my solution is to use that in place of `useProfile `. Also, my successful use of memoization with `useSubscribe ` is at `src/views/hellowWorld/testPage1/testPageBody.js`, which rerenders once with each new event received (as expected), but stops re-rendering after that (as expected). (Getting that to work was a very useful learning experience, btw!)

Any help will be appreciated!

**Comment by sepehr-safari** [comment]
> const { profile } = useProfile({ pubkey: '...' })

nothing wrong with this.

> the component being rerendered a little more than once per second, seemingly without end.

this is not related to your usage of `useProfile`, you should control rerenders from parent components, this component sounds good. there should be something wrong in their parents, causing rerenders.

**Comment by wds4** [comment]
I've tried this on multiple pages and the problem persists. If I put `const { profile } = useProfile({ pubkey: '...' })` inside the component, it triggers continuous rerenders, whether or not I use `profile` later in the component. If I comment out the one line like this: `\\ const { profile } = useProfile({ pubkey: '...' })` then the rerendering stops.

This problem doesn't happen with any of the other hooks from nostr-hooks. For now, my solution is to replace `useProfile` with my own customized code. 

If anybody has used `useProfile` successfully in a react component without this bug, please let me know so I can learn from it.

**Comment by sepehr-safari** [comment]
> If anybody has used useProfile successfully in a react component without this bug, please let me know so I can learn from it.

sure, check this out:
https://github.com/max21dev/groups/blob/main/src/shared/hooks/use-global-profile/index.ts

> const { profile } = useProfile({ pubkey: '...' })

maybe you need to wrap the whole object in a `useMemo` like this:
```ts
const params = useMemo(() => ({ pubkey: '...' }), []);
const { profile } = useProfile(params)
```
in a single line:
```ts
const { profile } = useProfile(useMemo(() => ({ pubkey: '...' }), []))
```

**Comment by wds4** [comment]
Looks like that works! But there's a twist.

What's the best way to pass data to useProfile: `{ pubkey }` or `params`? (See code below)

BOTH YIELD THE CORRECT PROFILE, AS EXPECTED. But `{ pubkey }` triggers rerenders whereas `params` does not. There might be a slight degradation in performance but you'd never realize your code is suboptimal without looking at the console. 

Why does this happen? I have no idea. Seems like there's a worthwhile learning point in there.

Here's my code:

```
import React, { useMemo } from 'react'
import { useProfile } from 'nostr-hooks'

const ProblemComponent = () => {
  // THIS FETCHES PROFILE CORRECTLY BUT CAUSES RERENDERS ABOUT 1 PER SECOND
  const pubkey = useMemo(
    () => '...',
    [],
  )
  const { profile } = useProfile({pubkey})

  // THIS FETCHES PROFILE CORRECTLY BUT WITHOUT CAUSING RERENDERS
  /*
  const params = useMemo(
    () => ({ pubkey: '...' }),
    [],
  )
  const { profile } = useProfile(params)
  */

  console.log('render ProblemComponent')

  return (
    <div>
      <p>name: {profile?.name}</p>
      <p>displayName: {profile?.displayName}</p>
      <p>website: {profile?.website}</p>
      <p>banner: {profile?.banner}</p>
      <p>about: {profile?.about}</p>
      <p>image: {profile?.image}</p>
    </div>
  )
}

export default ProblemComponent
```

**Comment by wds4** [comment]
Another detail:

Looks like `useMemo` is necessary but not sufficient to solve the problem. I had to make TWO changes:
- pass data into `useProfile` as `params` instead of `{ pubkey }` (where `pubkey = params.pubkey`)
- wrap `params` in `useMemo`

```
const ProblemComponent = () => {
  // THIS ALSO FETCHES PROFILE CORRECTLY BUT CAUSES RERENDERS ABOUT 1 PER SECOND
  const params = { pubkey: '...' }
  const { profile } = useProfile(params)

  console.log('render ProblemComponent')

  return (
    <div>
      <p>name: {profile?.name}</p>
      <p>displayName: {profile?.displayName}</p>
      <p>website: {profile?.website}</p>
      <p>banner: {profile?.banner}</p>
      <p>about: {profile?.about}</p>
      <p>image: {profile?.image}</p>
    </div>
  )
}

export default ProblemComponent
```

**Comment by sepehr-safari** [comment]
controlling rerenders in react is one of the most advanced topics, that's a portion of why I've created nostr-hooks, but seems like I need to make it even simpler than what it is 😁

first you need to learn about why we actually need a `useMemo` here, and why `useProfile` might cause unnecessary rerenders.

some times you have a dynamic component that needs to do something with a profile but you don't know which profile it is, because the pubkey dynamically changes on different situations as the user browse your app. so you need a component (let's say a custom hook) that receives a dynamic pubkey variable (let's say a string) and fetches fresh data as soon as that pubkey string changes (and do nothing when pubkey doesn't change). so you have something like this:

```ts
export const useUserProfile = ({ pubkey }: { pubkey: string | undefined }) => {
  // do something with pubkey here and return the result ...
};
```

assume that this is a custom hook to return profile of a pubkey. as soon as the pubkey changes on the fly (the one that comes from outside of the hook), this custom hook will be rerendered. this is pretty clear.

BUT things got crazy when you do something with that pubkey inside your custom hook. something like creating an object with it.

when you create an object inside your custom hook like this:
```ts
const obj = { pubkey };
```
this will create **A NEW OBJECT** on **EACH** rerender, **no matter if the pubkey is really changed or not**!
and since in JS/TS objects are passing by reference (not value), you will have **a new object of { pubkey } on each rerender, no matter if the pubkey really changed or not**!

so, that's why we need a `useMemo` to stop creating a new object on each rerender, and limit it to ONLY when the pubkey really changes.

the `useProfile` hook as well as some other hooks like `useSubscribe` is designed to be **reactive** on its input parameters.
so you need to pass a memoized object to it to control unnecessary rerenders.

at the moment the best practice is something like this:
```ts
export const useUserProfile = ({ pubkey }: { pubkey: string | undefined }) => {
  const { profile } = useProfile(
    useMemo(() => (pubkey ? { pubkey } : undefined), [pubkey]),
  );

  return { profile };
};
```

**Comment by wds4** [comment]
> controlling rerenders in react is one of the most advanced topics, that's a portion of why I've created nostr-hooks, but seems like I need to make it even simpler than what it is 😁

If you want a dummy like me to use it, then yeah 😝😂

Right now the sample README code for `Fetch Profile for a user` will trigger the error -- I would not know it's happening if I didn't specifically look for it. So that should probably be updated. (I'm happy to submit a PR if you'd like with your code from above)

> this will create A NEW OBJECT on EACH rerender,

I think I'm at least half following your explanation. But I'm trying to reproduce the error with some function other than `userProfile` and so far been unable to do it. In other words I want to replace this: `const { profile } = useProfile({ pubkey: '...' });` with this: `const { bar } = doSomething({ foo: '...' });` and see rerenders, but so far I can't do it. Maybe `doSomething` needs some async chicanery to cause a delay?

Thanks for working through this with me btw.
